name: Pylint

on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint --disable=missing-module-docstring,missing-class-docstring,missing-function-docstring,missing-docstring,invalid-encoded-data,no-member,too-few-public-methods --max-line-length=120 --load-plugins pylint_flask_sqlalchemy,pylint_flask `ls -R|grep .py$|xargs`
